table factOrderReviews
	lineageTag: 6a4beffb-34c3-40c6-a86f-af3c10c0eb3a

	column review_id
		dataType: string
		lineageTag: 773842b0-1786-44cc-acb4-ae29c19a4496
		summarizeBy: none
		sourceColumn: review_id

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		lineageTag: 2184c9d5-b1c4-431f-9f8d-dd9950b0ff5c
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column review_score
		dataType: int64
		formatString: 0
		lineageTag: e5e6088a-da2a-4956-9671-25e6a7cf1760
		summarizeBy: average
		sourceColumn: review_score

		annotation SummarizationSetBy = User

	column review_creation_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 8e5ae7b9-3929-4e5c-ae9c-a838971479bc
		summarizeBy: none
		sourceColumn: review_creation_date

		variation Variation
			isDefault
			relationship: ae2d3533-8b91-457d-abc7-4afcf65321d9
			defaultHierarchy: LocalDateTable_48dc1bc5-2f5e-461e-8cbe-caa83f66683b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Review Rating Category' =
			
			SWITCH(
			    TRUE(),
			    [review_score] = 5, "5 ★",
			    [review_score] = 4, "4 ★",
			    [review_score] = 3, "3 ★",
			    [review_score] = 2, "2 ★",
			    [review_score] = 1, "1 ★",
			    "Unrated"
			)
		lineageTag: e3ac8d13-8d3d-489f-b6c0-0eea428092f3
		summarizeBy: count

		annotation SummarizationSetBy = User

	column Rating
		dataType: string
		lineageTag: ba858eb7-a023-44aa-b9c3-a43b192e8521
		summarizeBy: none
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	partition factOrderReviews = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\guill\OneDrive\Desktop\PL300\olist overnight project\Data\olist_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type datetime}, {"review_answer_timestamp", type datetime}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"review_id", "order_id", "review_score", "review_creation_date"}),
				    #"Grouped Rows" = let
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type", {"review_id", "order_id", "review_score", "review_creation_date"}),
				
				    // Groups by order_id and takes top 1 row of each group
				    #"Grouped Rows" = Table.Group(#"Removed Other Columns", {"order_id"}, {
				        {"Data", each Table.FirstN(_, 1), type table [review_id=nullable text, order_id=nullable text, review_score=nullable number, review_creation_date=nullable datetime]}
				    }),
				
				    // Combines the 1-row tables back together
				    #"Combined Rows" = Table.Combine(#"Grouped Rows"[Data])
				in
				    #"Combined Rows",
				    #"Inserted Merged Column" = Table.AddColumn(#"Grouped Rows", "Rating", each Text.Combine({Text.From([review_score], "en-US"), " ★"}), type text)
				in
				    #"Inserted Merged Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

